### PR TITLE
Migrate build script to Kotlin DSL

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**

### CODE REVIEW

**Comment by Bnyro** [comment]
Have you actually tried to build the app? It doesn't seem to build at all after these changes...

**Comment by Jean-BaptisteC** [comment]
When I have time I rebase branch to trigger workflow

**Comment by Jean-BaptisteC** [comment]
The check failed because AGP 7.4.0 generate warnings -> more information here https://github.com/android/nowinandroid/issues/566

**Comment by Jean-BaptisteC** [comment]
@Bnyro any news?

**Pull request closed without merging**
