### PR TITLE
feat: more and improved resize options

### LINKED ISSUE #164: Some cropping options
### Describe your suggested feature

I would like you to introduce crop, stretch, fit, centre options for wallpaper, I request you .. 

### Other details

Thankyou

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Bnyro**
closes #164

### CODE REVIEW

**Comment by SuhasDissa** [comment]
I have noticed a few issues with this,
- Applying the effects doesn't seem to do any visual change (for both portrait and landscape wallpapers)
- The app crashes when trying to process large images (especially from reddit)
- This PR doesn't fix the original issue
   >When images are applied as wallpapers, the wallpaper should show the center of the image. However, all the resize options seems to set the top left part of the image as wallpaper.

**Comment by Bnyro** [comment]
> This PR doesn't fix the original issue 
> 
The zoom option does center it.

**Comment by SuhasDissa** [comment]
> > This PR doesn't fix the original issue 
> > 
> The zoom option does center it.

It didnt work when I tested it

**Comment by Bnyro** [comment]
Oh, I see where it's crashing for some reason.

**Comment by Bnyro** [comment]
> Applying the effects doesn't seem to do any visual change (for both portrait and landscape wallpapers)
>
This has been fixed with the previous commits.

> The app crashes when trying to process large images (especially from reddit)
>
I can't reproduce that, but I don't think that's caused by this PR.

**Pull request merged**
